In [2]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [3]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [4]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [5]:
x @ np.ones(3)

array([ 6., 15.])

In [6]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

array([[-5.98910458, -5.79968702,  5.33040868, -3.54502111, -0.4609759 ],
       [ 0.        , -6.26793371,  6.1209138 , -0.2013437 ,  0.81415118],
       [ 0.        ,  0.        , -2.76640645, -1.79078678,  1.979681  ],
       [ 0.        ,  0.        ,  0.        , -1.70693599, -3.2378658 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.42684022]])