<a href="https://colab.research.google.com/github/dm-fedorov/numpy_basic/blob/master/start_numpy/2.%20Введение%20в%20NumPy.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory" target="_blank"></a>

> © Семён Лукашевский [сайт автора](https://pyprog.pro/why_numpy.html)

Пожалуй, первое с чего стоит начать, так это с того, что массивы NumPy могут быть обычными операндами в математических выражениях:

In [1]:
import numpy as np

a = [1, 2, 3]    #  список Python
b = np.array([1, 2, 3])    #  массив NumPy
c = 7

In [2]:
#  Если мы умножим список на число, то...
a * c

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
#  Если попытаемся к списку это число прибавить, то
#  Python попытается выполнить конкатенацию, а не сложение.

In [4]:
#  Теперь умножим массив NumPy на число:
b * c

array([ 7, 14, 21])

In [5]:
#  Прибавим к массиву число:
b + c

array([ 8,  9, 10])

Для выполнения таких операций на Python, мы были вынуждены писать циклы. 

Писать такие циклы в NumPy, нет никакой необходимости, потому что все операции и так выполняются поэлементно:

In [6]:
a = np.array([[5, 7], [11, 13]])
a / 3 #  обычное деление

array([[1.66666667, 2.33333333],
       [3.66666667, 4.33333333]])

In [7]:
a // 3 #  целочисленное деление

array([[1, 2],
       [3, 4]])

In [8]:
a % 3 #  остаток от деления

array([[2, 1],
       [2, 1]])

In [9]:
a ** 3 #  возведение в степень

array([[ 125,  343],
       [1331, 2197]])

In [10]:
1 / a #  частное 1 и каждого элемента массива

array([[0.2       , 0.14285714],
       [0.09090909, 0.07692308]])

In [11]:
-a #  изменение знака элементов массива

array([[ -5,  -7],
       [-11, -13]])

Точно так же обстоят дела и с математическими функциями:

In [12]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [13]:
np.sin(a)    #  синус каждого элемента массива

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [14]:
np.log(a)    #  натуральный логарифм элементов массива

<ipython-input-14-8fecf66d4805>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)    #  натуральный логарифм элементов массива


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

Такие операции как `+=`, `-=`, `*=`, `/=` и прочие подобные, могут применяться к массивам и так же выполняются поэлементно. 

Они не создают новый массив, а изменяют старый:

In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [16]:
a += 2
a

array([3, 4, 5, 6, 7])

In [17]:
a *= 2
a

array([ 6,  8, 10, 12, 14])

In [18]:
#  Вещественный тип ('float64') не может быть 
#  преобразован в целочисленный ('int32'):
# a += b

In [19]:
#  А вот преобразование целочисленного типа в вещественный возможно
b += a
b

array([ 6.1,  8.2, 10.3, 12.4, 14.5])

При работе с массивами разного типа, тип результирующего массива приводится к более общему:

In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
b = np.linspace(0, 5, 5)
b

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [22]:
a.dtype

dtype('int64')

In [23]:
b.dtype

dtype('float64')

In [24]:
c = a + b
c

array([0.  , 2.25, 4.5 , 6.75, 9.  ])

In [25]:
c.dtype

dtype('float64')

Применение логических операций к массивам, так же возможно и так же выполняется поэлементно. 

Результатом таких операций является массив булевых значений (`True` и `False`):

In [26]:
a = np.array([2, 3, 5, 7, 11, 13])
a > 5

array([False, False, False,  True,  True,  True])

In [27]:
a == 7

array([False, False, False,  True, False, False])

In [28]:
b = np.array([2, 2, 5, 5, 11, 11])
a > b

array([False,  True, False,  True, False,  True])

In [29]:
a == b

array([ True, False,  True, False,  True, False])

Мы уже знаем что массив и число могут быть операндами самых разных математических выражений:

In [30]:
a = np.array([1, 2, 3])
(a + 3) * 7

array([28, 35, 42])

Операндами могут быть даже несколько различных массивов, правда их размеры должны быть одинаковыми:

In [31]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
a + b

array([4, 4, 4])

In [32]:
a ** b

array([1, 4, 3])

In [33]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
b = np.arange(9, 0, -1).reshape(3, 3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [35]:
a + b

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [36]:
a ** b

array([[   0,    1,  128],
       [ 729, 1024,  625],
       [ 216,   49,    8]])

Хотя, если честно, их размеры должны быть не равны, а должны быть совместимыми. 

Если их размеры совместимы, т.е. один массив может быть растянут до размеров другого, то в дело включается механизм транслирования массивов NumPy. 

Этот механизм очень прост, но имеет весьма специфичные нюансы. 

Рассмотрим простой пример:

In [37]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [39]:
c = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
c

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
a * b

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [41]:
a * c

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

В данном примере массив `b` может быть растянут до размеров массива `a` и станет абсолютно идентичен массиву `c`. 

Транслирование массивов невероятно удобно, так как позволяет избежать создания множества вложенных и невложенных циклов. 

К тому же в NumPy этот механизм реализован для максимально быстрого выполнения. Так что используйте транслирование везде, где это возможно в ваших вычислениях.

Вычисление суммы всех элементов в массиве и прочие унарные операции в NumPy реализованы как методы класса `ndarray`:

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a.sum()

45

In [44]:
a.min()

0

In [45]:
a.max()

9

По умолчанию, эти операции применяются к массиву, как к обычному списку чисел, без учета его ранга (размерности). 

Но если указать в качестве параметра одну из осей `axis`, то вычисления будут производиться именно по ней:

In [46]:
b = np.arange(16).reshape(4, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
b.sum(axis=0)    #  Сумма элементов каждого столбца

array([24, 28, 32, 36])

In [48]:
b.sum(axis=1)    #  Сумма элементов каждой строки

array([ 6, 22, 38, 54])

In [49]:
b.min(axis=1)    #  Минимальный элемент каждой строки

array([ 0,  4,  8, 12])

In [50]:
b.max(axis=0)    #  Максимальный элемент каждого столбца

array([12, 13, 14, 15])

### Значения -inf, inf и nan

Возможно вы обратили внимание на то, что когда мы вычисляли натуральный логарифм массива, среди значений которого был ноль, не появилось абсолютно никакой ошибки, а сам логарифм стал равен значению `-inf` (минус бесконечность). 

Убедимся в этом еще раз:

In [51]:
np.log(0)

<ipython-input-51-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

Более того, в NumPy мы даже можем делить на ноль:

In [52]:
a = np.array([0])
1 / a

<ipython-input-52-33a2b56b46e2>:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / a


array([inf])

NumPy предупредил нас о том, что встретил деление на ноль, но тем не менее выдал ответ `inf` (плюс бесконечность). 

Дело в том, что с математической точки зрения все абсолютно верно - если вы что-то делите на бесконечно малое значение, то в результате получете значение, которое окажется бесконечно большим. 

Если результатом математической операции является плюс или минус бесконечность, то логичнее выдать значение `inf` или `-inf`, чем выдавать ошибку.

В NumPy есть еще одно специальное значение - `nan`. Данное значение выдается тогда, когда результат вычислений не удается определить:

In [53]:
a = np.array([0, 1, np.inf])
a

array([ 0.,  1., inf])

In [54]:
np.cos(a)

<ipython-input-54-e6ad972c7c38>:1: RuntimeWarning: invalid value encountered in cos
  np.cos(a)


array([1.        , 0.54030231,        nan])

Заметьте, что NumPy нас просто предупредил о том, что ему попалось недопустимое значение, но ошибки не возникло. 

Дело в том, что в реальных вычислениях значения `nan`, `inf` или `-inf` встречается очень часто, поэтому появление этого значения проще обрабатывать специальными методами (функции `numpy.isnan()` и `numpy.isinf()`), чем постоянно лицезреть сообщения об ошибках.

Новичкам, довольно трудно привыкнуть, к тому что в недрах компьютера вся арифметика на самом деле является двоичной и с этим связано очень много казусов. 

Во-первых не совсем понятно, когда ждать появления значений `-inf` и `inf`:

In [55]:
np.cos(0)/np.sin(0)

<ipython-input-55-efe4113a919d>:1: RuntimeWarning: divide by zero encountered in double_scalars
  np.cos(0)/np.sin(0)


inf

In [56]:
np.sin(np.pi/2)/np.cos(np.pi/2)    #  ожидаем значение 0, но...

1.633123935319537e+16

Число `1.633123935319537e+16` появилось потому что в NumPy выполняются арифметические, а не символьные вычисления, т. е. число `π` хранится в памяти компьютера не как знание о том, что это математическая константа с бесконечным количеством десятичных знаков после запятой, а как обычное число с десятичной точкой (десятичная дробь) равная числу `π` с очень маленькой, но все же, погрешностью:

In [57]:
np.pi    #  значение числа pi в NumPy

3.141592653589793

Если из-за самых незначительных погрешностей вычисления все же возможны, то NumPy их обязательно выполнит. 

В этих случаях вместо значений `-inf` или `inf` у вас будут появляться самые маленькие или самые большие числа, которые возможно представить на вашем компьютере.

Если вам необходимы точные решения, то лучше обратиться к системам компьютерной алгебры и символьных вычислений, например пакету [SymPy](http://www.sympy.org/en/index.html). 

Если вы решили отправиться в самые дебри теории чисел, алгебры и криптографии, то лучшим решением окажется программа [GAP](http://www.gap-system.org/Overview/Capabilities/basic.html). 

Программа GAP не является программой Python, но имеет Python интерфейс в замечательной программе [Sage](http://www.sagemath.org/index.html), которая определенно заслуживает вашего внимания (см. [книгу](http://sagebook.gforge.inria.fr/english.html)).

### Линейная алгебра

[Много функций](https://pyprog.pro/linear_algebra_functions/linalg_functions.html).

Произведение одномерных массивов представляет собой скалярное произведение векторов:

In [58]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)

11

Произведение двумерных массивов по правилам линейной алгебры также возможно:

In [59]:
a = np.arange(2, 6).reshape(2, 2)
a

array([[2, 3],
       [4, 5]])

In [60]:
b = np.arange(6, 10).reshape(2, 2)
b

array([[6, 7],
       [8, 9]])

In [61]:
np.dot(a, b)

array([[36, 41],
       [64, 73]])

При этом размеры матриц (массивов) должны быть либо равны, а сами матрицы квадратными, либо быть согласованными, т.е. если размеры матрицы `А` равны `[m,k]`, то размеры матрицы `В` должны быть равны `[k,n]`:

In [62]:
a = np.arange(2, 8).reshape(2, 3)
a

array([[2, 3, 4],
       [5, 6, 7]])

In [63]:
b = np.arange(4, 10).reshape(3, 2)
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [64]:
np.dot(a,b)

array([[ 58,  67],
       [112, 130]])

Также по правилам умножения матриц, мы можем умножить матрицу на вектор (одномерный массив). 

При этом в таком умножении вектор столбец должен находиться справа, а вектор строка слева:

In [65]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [66]:
b = np.arange(4, 10).reshape(3, 2)
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [67]:
np.dot(a, b)

array([40, 46])

In [68]:
a = np.arange(1, 3).reshape(2, 1)
a

array([[1],
       [2]])

In [69]:
b = np.arange(4, 10).reshape(3, 2)
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [70]:
np.dot(b, a)

array([[14],
       [20],
       [26]])

Квадратные матрицы можно возводить в степень `n` т.е. умнажать сами на себя `n` раз:

In [71]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [72]:
np.dot(a, a)    #  Равносильно a**2

array([[ 7, 10],
       [15, 22]])

In [73]:
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [74]:
np.linalg.matrix_power(a, 0)

array([[1, 0],
       [0, 1]])

Довольно часто приходится вычислять ранг матриц:

In [75]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.linalg.matrix_rank(a)

2

In [77]:
b = np.arange(1, 24, 2).reshape(3, 4)
b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [78]:
np.linalg.matrix_rank(b)

2

Еще чаще приходится вычислять определитель матриц, хотя результат вас может немного удивить:

In [79]:
a = np.array([[1, 3], [4, 3]])
a

array([[1, 3],
       [4, 3]])

In [80]:
np.linalg.det(a)

-8.999999999999998

In [81]:
1*3 - 3*4    #  Результат должен быть целым числом

-9

В данном случае, из-за двоичной арифметики, результат нецелое число и округлять до ближайшего целого придется вручную. 

Это связано с тем, что алгоритм вычисления определителя использует [LU-разложение](https://ru.wikipedia.org/wiki/LU-%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5) - это намного быстрее, чем обычный алгоритм, но за скорость все же приходится немного заплатить ручным округлением (конечно, если таковое требуется):

In [82]:
np.linalg.det(a)

-8.999999999999998

In [83]:
round(np.linalg.det(a))

-9.0

In [84]:
b = np.arange(1, 48, 3).reshape(4, 4)
b

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

In [85]:
np.linalg.det(b)

0.0

In [86]:
round(np.linalg.det(b))

0.0

Транспонирование матриц:

In [87]:
a

array([[1, 3],
       [4, 3]])

In [88]:
a.T

array([[1, 4],
       [3, 3]])

Вычисление обратных матриц:

In [89]:
a

array([[1, 3],
       [4, 3]])

In [90]:
b = np.linalg.inv(a)
b

array([[-0.33333333,  0.33333333],
       [ 0.44444444, -0.11111111]])

In [91]:
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

Решение систем линейных уравнений:

In [92]:
#  система из двух линейных уравнений:
#  1*x1 + 5*x2 = 11
#  2*x1 + 3*x2 = 8
a = np.array([[1, 5], [2, 3]])
b = np.array([11, 8])

In [93]:
x = np.linalg.solve(a, b)
x

array([1., 2.])

In [94]:
np.dot(a, x)

array([11.,  8.])

### Статистика

[Элементарные статистические функции](https://pyprog.pro/statistics_functions/statistics_function.html):

In [95]:
a = np.random.randint(20, size=(5, 5))
a

array([[ 8, 15,  2, 18,  0],
       [ 3,  7, 15, 13,  6],
       [18, 10,  9,  4, 17],
       [17, 18, 19, 13,  8],
       [16, 12, 11,  7,  3]])

In [96]:
np.amin(a)    #  Минимальный элемент массива

0

In [97]:
np.amax(a)    #  максимальный элемент

19

In [98]:
np.amin(a, axis=0)  #  минимальный элемент вдоль первой оси (столбцы)

array([3, 7, 2, 4, 0])

In [99]:
np.amin(a, axis=1)  #  минимальный элемент вдоль второй оси (строки)

array([0, 3, 4, 8, 3])

In [100]:
#  Процентили:
np.percentile(a, 25)

7.0

In [101]:
np.percentile(a, 50)

11.0

In [102]:
np.percentile(a, 75)

16.0

Средние значения элементов массива и их отклонения:

In [103]:
a = np.random.randint(13, size=(5, 5))
a

array([[ 3,  5, 10, 10,  9],
       [10,  9,  1,  4,  0],
       [ 5,  7,  0,  9,  4],
       [10,  8,  9,  7,  2],
       [10,  1,  9,  7,  6]])

In [104]:
np.median(a)    #  медиана элементов массива

7.0

In [105]:
np.mean(a)    #  среднее арифметическое

6.2

In [106]:
np.var(a)    #  дисперсия

11.52

In [107]:
np.std(a)    #  стандартное отклонение

3.394112549695428

Корреляционные коэфициенты и ковариационные матрицы величин:

In [108]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])
z = np.array([29, 22, 24, 20, 18, 14, 16, 11, 9, 10])

In [109]:
#  Линейный коэфициент корреляции Пирсона
#  величин 'x' и 'y'

XY = np.stack((x, y), axis=0)
XY

array([[ 1,  4,  3,  7, 10,  8, 14, 21, 20, 23],
       [ 4,  1,  6,  9, 13, 11, 16, 19, 15, 22]])

In [110]:
np.corrcoef(XY)

array([[1.        , 0.93158099],
       [0.93158099, 1.        ]])

In [111]:
#  Кросс-корреляции:
np.correlate(x, y)

array([1736])

In [112]:
np.correlate(x, z)

array([1486])

In [113]:
#  Ковариационные матрицы:
np.cov(XY)

array([[63.65555556, 49.82222222],
       [49.82222222, 44.93333333]])

In [114]:
np.cov(x)

array(63.65555556)

Так же NumPy предоставляет функции для вычисления гистограмм наборов данных различной размерности и некоторые другие статистичские функции.

### Генерация случайных значений

Получение простых случайных данных:

In [115]:
np.random.rand()    #  случайное число от 0 до 1

0.16048016603489945

In [116]:
np.random.rand(10)    #  одномерный массив случайных значений

array([0.37363098, 0.18293017, 0.33368838, 0.20369677, 0.51855123,
       0.15153137, 0.23697608, 0.08544395, 0.18301854, 0.09957913])

In [117]:
np.random.rand(3, 4)    #  двумерный массив случайных значений

array([[0.32707583, 0.96676171, 0.3823631 , 0.28383011],
       [0.90472129, 0.50113339, 0.10620564, 0.59158263],
       [0.52778843, 0.40360622, 0.93310452, 0.37154915]])

In [118]:
np.random.randn(10)    #  случайные значения с нормальным распределением

array([-0.22445671,  0.04530213, -1.10597734,  1.00371757, -2.21259254,
        0.80314034,  0.90013657,  2.04839572, -0.86648608,  0.02818831])

In [119]:
np.random.randint(10)    #  случайное целое число от 0 до 10

8

In [120]:
np.random.randint(10, 100)    #  случайное целое число от 10 до 100

89

In [121]:
np.random.randint(10, size=7)    #  одномерный массив случайных целых чисел

array([4, 4, 7, 6, 8, 6, 6])

In [122]:
np.random.randint(10, size=(4, 4))    #  двумерный массив случайных целых чисел

array([[1, 2, 2, 0],
       [6, 7, 2, 1],
       [4, 0, 1, 1],
       [4, 1, 4, 8]])

Перестановки:

In [123]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [124]:
np.random.shuffle(x)    #  перетасовывает содержимое массива
x

array([1, 0, 4, 5, 6, 2, 3])

In [125]:
np.random.permutation(7)    #  выполняет тоже самое, не требуя входного массива

array([4, 3, 1, 0, 5, 2, 6])

In [126]:
y = np.arange(9).reshape(3, 3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
np.random.shuffle(y)    #  перестановки выполняются только по 1-й оси

NumPy предоставляет [порядка 30 функций](https://pyprog.pro/random_sampling_functions/random_sampling_functions.html), позволяющих генерировать случайные числа с самыми разными вероятностными распределениями:

In [128]:
np.random.beta(0.1, 0.6, size=5)    #  бета распределение

array([5.73766177e-01, 5.09876142e-07, 9.24610227e-09, 2.53818646e-01,
       1.33500226e-01])

In [129]:
np.random.gamma(shape=0.8, scale=1.7, size=5)    # гамма распределение

array([0.56810385, 3.18502045, 5.74201242, 1.73110794, 4.64109634])

In [130]:
np.random.pareto(3.5, size=5)    #  Паретто распределение

array([0.00966924, 0.4382534 , 0.01559033, 0.00542235, 0.32482615])

In [131]:
np.random.chisquare(2.2, size=5)     #  хи-квадрат распределение

array([0.57971816, 1.44661752, 1.82792015, 7.99204351, 0.45010319])

Вы так же имеете доступ к состоянию генератора случайных чисел, а так же можете управлять им:

In [132]:
#np.random.get_state()    #  Вы можете узнать состояние генератора

In [133]:
np.random.seed(123)    #  устанавливает состояние генератора

In [134]:
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

### Множества

В случаях, когда массивы содержат очень много элементов, среди которых есть одинаковые, возникает задача поиска уникальных элементов, количества их вхождений в исходный массив:

In [135]:
x = np.array([1, 2, 1, 2, 3, 1])
np.unique(x)

array([1, 2, 3])

In [136]:
np.unique(x, return_counts=True)    #  количество вхождений

(array([1, 2, 3]), array([3, 2, 1]))

В двумерных и многомерных массивах уникальные массивы можно искать, как по всему множеству его значений, так и по отдельным осям:

In [137]:
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2]])
x

array([[0, 1, 1, 2],
       [0, 1, 1, 2],
       [9, 1, 1, 2]])

In [138]:
np.unique(x, axis=0)    #  множество уникальных строк

array([[0, 1, 1, 2],
       [9, 1, 1, 2]])

In [139]:
np.unique(x, axis=1)    #  множество уникальных столбцов

array([[0, 1, 2],
       [0, 1, 2],
       [9, 1, 2]])

Так же имеется ряд других полезных функций:

In [140]:
X = np.array([0, 2, 4, 6, 8])
Y = np.array([0, 3, 4, 6, 7])

In [141]:
np.in1d(X, Y)    #  наличие элементов из X среди элементов Y

array([ True, False,  True,  True, False])

In [142]:
np.intersect1d(X, Y)    #  пересечение множеств элементов массивов

array([0, 4, 6])

In [143]:
np.setdiff1d(X, Y)    #  разность множеств

array([2, 8])

In [144]:
np.setxor1d(X, Y)    #  симметрическая разность (исключающее или)

array([2, 3, 7, 8])

In [145]:
np.union1d(X, Y)     #  объединение множеств

array([0, 2, 3, 4, 6, 7, 8])

### Логические операции

Логические функции NumPy, условно, можно разделить на два множества: первое - позволяет определять специфику элементов массива и самого массива; второе - обычные логические операции, которые действуют над массивами поэлементно.

Иногда, возникает потребность определить тип элементов:

In [146]:
A = np.array([-np.inf, np.inf, np.nan, -1, 0, 1, 1.47, 2, 3 + 2j])

In [147]:
np.isfinite(A)    #  Все ли элементы в A числа?

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [148]:
np.isinf(A)    #  Есть ли в A бесконечности?

array([ True,  True, False, False, False, False, False, False, False])

In [149]:
np.isnan(A)    #  Есть ли в A значения nan?

array([False, False,  True, False, False, False, False, False, False])

In [150]:
np.iscomplex(A)    #  есть ли в A комплексные числа?

array([False, False, False, False, False, False, False, False,  True])

In [151]:
np.isreal(A)    #  Есть ли в A вещественные числа?

array([ True,  True,  True,  True,  True,  True,  True,  True, False])

Привычные нам логические операции выполняются над массивами булевых значений (массивы из значений True и False):

In [152]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

In [153]:
np.logical_and(X, Y)    #  логическое "И"

array([ True, False, False, False])

In [154]:
np.logical_or(X, Y)    #  логическое "ИЛИ"

array([ True,  True,  True, False])

In [155]:
np.logical_not(X)    #  логическое "НЕ"

array([False,  True, False,  True])

In [156]:
np.logical_xor(X, Y)    # исключающее "ИЛИ"

array([False,  True,  True, False])

Помимо всего прочего, NumPy позволяет производить различные сравнения:

In [157]:
np.allclose([1, 2, 3], [1, 2, 2.99999])    #  Являются ли значения массивов близкими?

True

In [158]:
x = np.random.randint(4, size=5)
x

array([3, 1, 2, 1, 0])

In [159]:
y = np.random.randint(4, size=5)
y

array([1, 2, 3, 1, 0])

In [160]:
np.greater(x, y)    #  поэлементное x > y 

array([ True, False, False, False, False])

In [161]:
np.less(x, y)    #  поэлементное x < y

array([False,  True,  True, False, False])

In [162]:
np.equal(x, y)    #  поэлементное x == y

array([False, False, False,  True,  True])