<a href="https://colab.research.google.com/github/dm-fedorov/numpy_basic/blob/master/start_numpy/3.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory" target="_blank"></a>

> © Семён Лукашевский [сайт автора](https://pyprog.pro/why_numpy.html)

### Индексация, срезы, итерирование

Одномерные массивы очень похожи на простые списки Python:

In [1]:
import numpy as np

a = np.arange(12) ** 2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [2]:
#  Обратиться к элементу можно по его индексу
a[0]

0

In [3]:
a[-1]

121

In [4]:
#  Извлечение срезов по двум индексам массива
a[4:8]

array([16, 25, 36, 49])

In [5]:
a[:6], a[6:]

(array([ 0,  1,  4,  9, 16, 25]), array([ 36,  49,  64,  81, 100, 121]))

In [6]:
#  Извлечение элементов с определенным шагом
a[::3]

array([ 0,  9, 36, 81])

In [7]:
a[::-1]    #  элементы массива в обратном порядке

array([121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [8]:
#  Каждому второму элементу можно присвоить значение
a[:12:2] = -1

In [9]:
a

array([ -1,   1,  -1,   9,  -1,  25,  -1,  49,  -1,  81,  -1, 121])

Многомерные массивы имеют один индекс на одну ось, поэтому обращение к элементам и извлечение срезов производится не по одному, а по нескольким индексам:

In [10]:
a = np.arange(27).reshape(3, 9)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [11]:
a[0, 0]

0

In [12]:
#  В качестве срезов можно извлекать как столбцы так и строки
a[:, 0]    #  Извлекаем столбец, равносильно a[0:3, 0]

array([ 0,  9, 18])

In [13]:
a[:, 1]

array([ 1, 10, 19])

In [14]:
a[1:3, 2]    #  Можно извлечь часть столбца

array([11, 20])

In [15]:
a[0]    #  Извлекаем строку, равносильно a[0, :]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a[0, 2:7]    #  Можно извлечь часть строки

array([2, 3, 4, 5, 6])

In [17]:
a[2, 4:5]

array([22])

Те же правила действуют и для многомерных массивов. 

### Дополнительные возможности индексирования

Работая с последовательностями: строками, списками или кортежами, мы привыкли только к одному единственному способу индексирования, который предлагает нам Python. 

Неужели это можно сделать как-то по другому? 

Оказывается можно, и, иногда это оказывается гораздо удобнее, чем может показаться. 

Помимо индексирования целыми числами и срезами, к которому мы так сильно привыкли, NumPy предлагает еще два необычных метода индексирования. 

Первый - это индексация с помощью массивов целых чисел, а второй - это индексация с помощью массивов булевых значений.

### Индексирование массивами целых чисел
Что такое массив индексов? 

Массив индексов - это обычный массив (последовательность) целых чисел, причем каждое число соответствует некоторому индексу определенного элемента в другом массиве, например:

In [18]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
i = np.array([1, 1, 1, 9, 8, 5])
i

array([1, 1, 1, 9, 8, 5])

In [20]:
b = a[i]
b

array([11, 11, 11, 19, 18, 15])

Но на практике гораздо удобнее использовать в качестве массивов индексов списки Python. Относительно вышеприведенного примера это будет выглядеть следующим образом:

In [21]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
a[[1, 1, 1, 5, 8, 9]]

array([11, 11, 11, 15, 18, 19])

### Индексация массивами булевых значений

Булевых значений всего два, это `False` и `True`. 

Возникает весьма интересный вопрос, как с помощью таких массивов выполняется индексация, ведь они состоят из одних лишь логических значиний. 

И снова, оказывается не только возможно, но и крайне удобно в некоторых случаях:

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a[np.array([False, True, True, False, True])]

array([1, 2, 4])

In [25]:
a = np.arange(18).reshape(3, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [26]:
a[a % 2 == 0]    #  Создадим булев массив

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [27]:
a[a % 2 == 0] = -1     #  Заменим все четные числа на -1

In [28]:
a

array([[-1,  1, -1,  3, -1,  5],
       [-1,  7, -1,  9, -1, 11],
       [-1, 13, -1, 15, -1, 17]])

In [29]:
a[a > 1]

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [30]:
a

array([[-1,  1, -1,  3, -1,  5],
       [-1,  7, -1,  9, -1, 11],
       [-1, 13, -1, 15, -1, 17]])

In [31]:
a[(0 < a) & (a < 20)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

### Манипулирование формой массивов

Форму массива определяет количество элементов вдоль каждой оси:

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
a.shape    #  Узнаем форму массива

(4, 3)

In [34]:
a.ravel()    #  "Сплющивает" массив до одной оси

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Изменить форму массива можно разными способами:

In [35]:
a.reshape(2, 6)    #  Возвращает массив с измененной формой

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [36]:
a.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a.T    #  Возвращает транспонированный массив

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [38]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Важно понимать, что функция `reshape` не изменяет исходный массив. 

Если же вам необходимо изменить форму существующего массива, то можно воспользоваться методом `resize`.

In [39]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
a.resize((2, 6))

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Если в функции `reshape` один из размеров задать равным `-1`, то этот размер будет вычислен автоматически:

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [43]:
a.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Объединение массивов

Объединение массивов возможно по разным осям:

In [45]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [46]:
b = np.arange(6, 10).reshape(2, 2)
b

array([[6, 7],
       [8, 9]])

In [47]:
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

In [48]:
np.hstack((a, b))

array([[0, 1, 6, 7],
       [2, 3, 8, 9]])

Как видим функция `vstack` объединяет массивы по вертикали, а `hstack` - по горизонтали. Причем количество элементов вдоль объединяемых осей должно быть одинаковым.

Функция `column_stack` представляет одномерные массивы в виде столбцов после чего объединяет их. 

Для двумерных массивов `column_stack` эквивалентна `hstack`:

In [49]:
a = np.arange(2)
a

array([0, 1])

In [50]:
b = np.arange(2, 4)
b

array([2, 3])

In [51]:
np.column_stack((a, b))

array([[0, 2],
       [1, 3]])

Функция `row_stack` эквивалентна `vstack` для любых входных массивов:

In [52]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [53]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [54]:
np.row_stack((a, b))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Есть еще один способ быстро объединять и создавать массивы - это объекты `r_` и `c_`. 

Они позволяют объединить массивы вдоль одной оси или позволяют создать новый массив с использованием операций среза.

In [55]:
np.r_[0:5]    #  Создает массив из среза

array([0, 1, 2, 3, 4])

In [56]:
np.r_[0:5, 3, 2, 1, 0]    #  Создает массив из среза и последовательности

array([0, 1, 2, 3, 4, 3, 2, 1, 0])

In [57]:
np.c_[0:5]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### Разделение массивов

Разделить массив вдоль горизонтальной оси можно с помощью функции `hsplit`, а вдоль вертикальной `vsplit`:

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

### Копии и представления массивов

Вы, может быть уже заметили, что некоторые функции, что-то делают с массивом, возвращают какой-то результат, но при этом с исходным массивом ничего не происходит. 

Например:

In [60]:
a = np.arange(18).reshape(3, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [61]:
a.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [62]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

Дело в том, что в NumPy существует два понятия: *копия массива* и *представление массива*. 

Попробуем разобраться на примерах.

In [63]:
a = np.arange(18).reshape(3, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [64]:
b = a
c = a.T

In [65]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [66]:
c

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [67]:
a[0, 0] = -1

In [68]:
a

array([[-1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [69]:
b

array([[-1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [70]:
c

array([[-1,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

Хорошо, `a` и `b` - это адреса (указатели) одного и того же массива. 

Как быть с переменной `с`? 

По сути это тоже указатель, который ссылается на ту же самую область памяти с данными, на которую ссылаются `a` и `b`, но представлены эти данные в другой форме. 

Поэтому в NumPy и существует понятие - *представление массива*. 

Действительно, одни и те же данные могут быть представлены в разной форме:

In [71]:
a = np.arange(18).reshape(3, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [72]:
b = a.reshape(2, 9)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [73]:
c = a.reshape(2, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [74]:
#  Но если изменить один элемент через а
#  то это отразится во всех представлениях

a[0, 0] = 7777

In [75]:
b

array([[7777,    1,    2,    3,    4,    5,    6,    7,    8],
       [   9,   10,   11,   12,   13,   14,   15,   16,   17]])

In [76]:
c

array([[[7777,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8]],

       [[   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17]]])

Простое присваивание не делает никаких копий массива - это первое, о чем нужно помнить. 

Поэтому отсутствие автоматического копирования при присваивании - небольшая плата за простоту и легкость Python.

In [77]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
b = a
b is a

True

In [79]:
id(a), id(b)

(140645171005840, 140645171005840)

Довольно часто, необходимо сделать полную копию массива и метод `copy` позволяет сделать это, причем скопировать не только данные массива, но и все его свойства.

In [80]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [81]:
c = a

In [82]:
b = a.copy()

In [83]:
a[0, 0] = 79
a

array([[79,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [84]:
c

array([[79,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [85]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

Теперь мы знаем, что простое присваивание не выполняет копирования массивов. 

Если нам нужна копия, то мы можем легко сделать ее с помощью метода `copy`. 

Однако, бывают случаи когда копия массива не нужна, а нужен тот же самый массив, но с другими размерами - другое представление исходного массива.

Для таких нужд NumPy предоставляет метод `ndarray.view()`. 

Этот метод создает новый объект массива, который просматривает данные исходного массива, но изменение размеров одного массива не повлечет изменение размеров другого.

In [86]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
b = a

In [88]:
a.shape = 3, -1     #  Меняем размеры массива "а"

In [89]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
#  Теперь создадим представление массива "а"
c = a.view()

In [91]:
a.shape = 2, -1    #  Изменим размеры массива "а"

In [92]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [94]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [95]:
a[0,0] = 3242

In [96]:
c

array([[3242,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

Как правило, функции меняющие форму и порядок элементов в массивах возвращают именно представление, а не копию массива:

In [97]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [98]:
b = a.reshape(2, 4)    #  Массив "b" - это представление массива "а"

In [99]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
c = b.T    #  А вот массив "с" - это представление массива "b"

In [101]:
c

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [102]:
c[0,0] = 888

In [103]:
a

array([888,   1,   2,   3,   4,   5,   6,   7])

In [104]:
b

array([[888,   1,   2,   3],
       [  4,   5,   6,   7]])

Срезы массивов - это тоже представления массивов:

In [105]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
b = a[0:12:2]
b

array([ 0,  2,  4,  6,  8, 10])

In [107]:
a[:] = 0

In [108]:
b

array([0, 0, 0, 0, 0, 0])

Если мы говорим, что массив `b` - это представление массива `a`, то подразумевается, что независимо от формы и вида массива `b` он состоит из тех же данных в памяти, что и массив `a`. 

Поэтому изменение элементов в одном из них повлечет изменение соответствующих элементов в другом.